### ISSUE TITLE
포크된 저장소를 포크하는 것이 안되어 문의 드립니다.

### ISSUE THREAD

**Issue by calvinsnax** [rx-public/rxp_flex#2]
안녕하세요. 아무래도 BNU님의 개선판이 라이믹스 2.0의 지향점과 같고 기존코드보다 훨씬 안정적이라 생각하여 본 소스를 기반으로 새로운 디자인의 테마를 제작하고자 합니다. 이미 제 저장소에서 포크된 저장소라서 그런지 제 쪽에서 이 소스를 다시 포크할 수는 없더라구요...ㅠ 따라서 복사 후 새로운 저장소로 생성하고자 하는데 이전에 동의를 구하고자 이슈 올립니다.

**Comment by bnu** [comment]
물론이죠! 영광입니다.
